apiVersion: v1
kind: List
items:
- kind: Namespace
  apiVersion: v1
  metadata:
    name: azure-service-operator

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: armtemplate.service-operator.azure
  spec:
    group: service-operator.azure
    names:
      kind: CloudFormationTemplate
      listKind: CloudFormationTemplateList
      plural: cloudformationtemplates
      shortNames:
      - cft
      - cfts
      - cfn
      - cfns
      - cloudformation
      singular: cloudformationtemplates
    scope: Namespaced
    version: v1alpha1    
